### ISSUE TITLE
Export a dojo-based bundle as a library

### ISSUE THREAD

**Issue by HeikoStudt** [OpenNTF/dojo-webpack-plugin#305]
We have got two different dojo applications (A, B) twingled, where a part of the B is currently included as a "plugin" into A.
We are modifying B (as an application) to be bundled by webpack which works quite well using this plugin.
However, B wants to expose this "plugin" part as a own bundle as a library.
We are able to create that second bundle, but the generation always adds dojo as the module.exports, instead of the entry plugin.js.

The relevant generated "exporting" part is:

```
/***/ 0:
/*!****************************************************************************************************************!*\
  !*** multi (webpack)/hot/dev-server.js ./plugin.js /tmp/tmp-3867Oc5Vjhcfs1M0/dojo/dojo.js ***!
  \****************************************************************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

__webpack_require__(/*! /home//node_modules/webpack/hot/dev-server.js */"./node_modules/webpack/hot/dev-server.js");
__webpack_require__(/*! ./plugin.js */"./plugin.js");
module.exports = __webpack_require__(/*! /tmp/tmp-3867Oc5Vjhcfs1M0/dojo/dojo.js */"../../../../tmp/tmp-3867Oc5Vjhcfs1M0/dojo/dojo.js");

/***/ }),
```

I would think, module.exports = should be one line above, exporting everything plugin.js offers.
I might miss a point of the dojo runtime/loader being necessary for something, but that one has mostly noop-code and I thought that it is only necessary for the webpack magic to work?

Do someone know, how to export the real plugin instead of dojo or, as a workaround, how to modify the plugin loading to choose the export? We are able to modify application A (to a smaller extend).

MFG (Kind regards)

**Comment by HeikoStudt** [comment]
These additional dependencies (loader and, if that is a module, loaderConfig) are added in lib/DojoLoaderPlugin.js::succeedModule. 
Probably so that the chunks are inserted in case they are needed someplace. However, I did not understand whether they are needed at this exact place or at all for our use-case.
In webpack/lib/DependenciesBlock.js there is no obvious way to insert a dependency at a different place.

**Comment by HeikoStudt** [comment]
Below is a dirty workaround, interfering with their internal dependencies field directly. However, after this change, we could rightly import plugin-library and so it solved our problem.
I am not sure, whether there is a need to open an issue at webpack to insert some API for this use case or if this project did something silly and the effect for the loader and config being added as a dependency in this place could be archived more easily.

Please give advice for the direction to go further.

lib/DojoLoaderPlugin.js
```js
succeedModule(module) {
 const {options} = this;
 if (!module.issuer) {
  // workaround so that the entry stays last and is exported
  var plugin = module.dependencies.pop()
  module.addDependency(new CommonJsRequireDependency(options.loader));
  if (util.isString(options.loaderConfig)) {
    module.addDependency(new
       CommonJsRequireDependency(options.loaderConfig));
  }
  // workaround so that the entry stays last and is exported
  module.dependencies.push(plugin)
 }
}
```

MFG (kind regards)

**Comment by HeikoStudt** [comment]
Dear chuckdumont,

thanks for your reply and work.
In our plugin "B" we are packing some service access plugin object together with some configuration Dojo GUI elements. Application "A" is require()ing the plugin as a module and showing the GUI on entering the plugin's configuration. 
For being able to access the plugin's module, that one needs to be exported by webpack. Instead, the dojo loader (or the loader config) module is exported. It is the content of import()ing the bundle in the debugger, if we were using the libraryTarget "var".

What part of the webpack config are you interested in? Currently I can't access the file while needing to pseudonymize anyway, so I have tried to outline an example out of my memory. If you need any more or detailed information, please let me know and I will provide it.

```webpack.config.js
var path = require('path');

module.exports = {
  entry: {  main: './app.js', plugin: './plugin.js'},
  output: {
    path: path.resolve(__dirname, 'dist'),
    filename: '[name].bundle.js',
    libraryTarget: 'var',
    library: ['MyLibrary', '[name]'],
  },
  Module: {}, // ommitted
  Plugin: [
    new DojoWebpackPlugin({
      loaderConfig: { ... }, // object, otherwise it adds the config as a second module and exports this instead
      //...
    }),
  }, // more parts ommitted
};
```


MFG (kind regards)

**Comment by chuckdumont** [comment]
I think the issue is that you're declaring plugin.js to be an entry bundle.  Entry bundles are loaded on their own (not by other bundles) and include the runtime dependencies for webpack and dojo-webpack-plugin.  It sounds like you want your plugin.js bundle to be a vendor or shared library.  In that case, it would only be loaded by other applications (including application B's app.js).  In that case, you wouldn't declare plugin.js to be an entry bundle. 

See [Authoring Libraries](https://webpack.js.org/guides/author-libraries/) and [Sharing a webpack vendor bundle across applications](https://neemzy.org/articles/sharing-a-webpack-vendor-bundle-across-applications) for tips.

**Comment by HeikoStudt** [comment]
Thanks for your links. I had read them before and tried once again, but cannot see your point yet:
 * The "authoring libraries" one is the exact thing we are doing, isn't it? In that example there is the entry './src/index.js', which is our plugin.js, and they put "library" and "libraryTarget" as we did.

* The other link is about putting these into "common chunks" for performance consideration!?

As our plugin is including Dojo/Dijit modules including its i18n and AMD-style classes for the configuration GUI, we need the dojo-webpack plugin to package our plugin. Am I wrong with this assumption?


Thanks again,
MFG (kind regards)

**Comment by HeikoStudt** [comment]
I have created a minimalistic version of our stuff: https://github.com/HeikoStudt/dojo-webpack-issue305-test

npm install
npm run serve && open http://localhost:8080/index.html
edit node_modules/dojo-webpack/lib/DojoLoaderPlugin.js
npm run serve && open http://localhost:8080/index.html

Thanks for your time again,
MfG (kind regards)

**Comment by chuckdumont** [comment]
I tried your test case but I don't see the behavior you described.  The app seemed to work the same with, or without, the work-around you proposed.

At any rate, I think I have a fix that will work for you.  Please try version 2.8.18-rc1 and see how it goes.  It's a variation on your work-around (just adds the dojo deps earlier so they aren't at the top of the dependencies list).

**Comment by HeikoStudt** [comment]
In my test case app, you got different output before/after my dirty fix. However, I was too minimalistic in the output. :-)
I've enhanced the test app with better output and a Readme.md on how to reproduce.

Your change did not fix the problem, either. I peeked a bit into webpack - it is sorting the dependencies after the build-module step and before succeed-module (Compilation.js). Perhaps we could utilize this somehow?
However, your fix broke my dirty workaround.

Can you please have another look into my test app?

Thanks a lot,
MFG (Kind regards)

**Comment by chuckdumont** [comment]
Please try version 2.8.18-rc2.  It fixes your test case, at least.

**Comment by HeikoStudt** [comment]
Hello chuckdumont,

in npm run serve it looks great. In debug build it looks correct as well. We will test in our code as soon as possible.
Glimpsing in the code change it looks like a hell of a workaround!? :-/

Thanks again,
MFG (Kind regards)

**Comment by chuckdumont** [comment]
Fixed in v2.8.18

**Comment by HeikoStudt** [comment]
We can confirm that our problem is solved, thanks! My apologies for testing it so late.

For any googler: Additionally we needed to use the ScopedRequirePlugin for not canibalizing our app A's global require function and furthermore UMD (instead of var) for being able to use it with the dojo-loader of A.

MFG (kind regards)

**Comment by HeikoStudt** [comment]
Yet more facts for the occasional Googler:
1. Additionally, you need to set "noGlobals" in dojo.config for dojo, dijit, dojox variables to be separated
2. However, you still get some global namespace problems in "domConstruct::toDom", e.g. using new TextBox() it will gets some cache-ID from application A while reading the cache of application B. This is due to us using two different dojo instances in the two applications.
It somewhat works by integrating the application B's AMDs into application A's registry with a SED of the namespaces, circumventing the dojo-webpack approach.

However, we added an iframe-abstraction around our API and got clean.

**Comment by chuckdumont** [comment]
@HeikoStudt - Thanks for the tips!
